version: "3.9"

services:
  api-1:
    image: rinha
    hostname: api-1
    build:
      dockerfile: ./Dockerfile
    container_name: rinha-api-1
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "200MB"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - rinha-network

  api-2:
    image: rinha
    hostname: api-2
    build:
      dockerfile: ./Dockerfile
    container_name: rinha-api-2
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "100MB"
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - rinha-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "100MB"
    networks:
      - rinha-network

  postgres-db:
    image: "postgres:latest"
    hostname: postgres-db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "140MB"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rinha-db

    # se quer apelar, use: postgres -c 'max_connections=30' 'fsync=off' -c 'synchronous_commit=off' -c 'checkpoint_timeout=1d' -c 'full_page_writes=false'
    command: postgres -c 'max_connections=400'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d rinha-db" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - rinha-network

networks:
  rinha-network:
    driver: bridge
