version: "3.9"

services:
  api-1:
    image: rinha
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8081:8080"
    hostname: api-1
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.6GB"
    depends_on:
      - postgres-db
    networks:
      - rinha-network

  api-2:
    image: rinha
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8082:8080"
    hostname: api-2
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "0.6GB"
    depends_on:
      - postgres-db
    networks:
      - rinha-network

  postgres-db:
    image: "postgres:latest"
    hostname: postgres-db
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "1.3GB"
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rinha-db
    # healthcheck:
    #   test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 3
    networks:
      - rinha-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
      - postgres-db
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "0.5GB"
    networks:
      - rinha-network

networks:
  rinha-network:
    driver: bridge
